# Generated by Django 3.1.4 on 2021-12-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211229_2157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingDetails',
            new_name='ShippingDetail',
        ),
        migrations.AddField(
            model_name='addproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
