# Generated by Django 3.1.4 on 2022-04-02 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211229_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingdetail',
            old_name='country',
            new_name='region',
        ),
    ]
