# Generated by Django 3.1.4 on 2022-04-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220402_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingdetail',
            old_name='zipCode',
            new_name='postalCode',
        ),
    ]
