# Generated by Django 3.1.4 on 2022-04-12 17:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_product_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variation',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XL', 'XL'), ('SM', 'SM')], max_length=5),
        ),
    ]
