# Generated by Django 3.1.4 on 2023-05-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20220412_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variation',
        ),
    ]
