# Generated by Django 3.1.4 on 2023-05-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_product_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
